<a href="https://colab.research.google.com/github/chatterjeerajdeep/explore-machine-learning/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')

## Let's get some information about the data

In [4]:
print("This data set has {0} rows and {1} columns".format(dataset.shape[0], dataset.shape[1]))
print("#"*10)
print("The columns present in the data set are {}".format(dataset.columns))
print("#"*10)
print("The description of the data is \n {}".format(dataset.describe()))
print("#"*10)

This data set has 10 rows and 4 columns
##########
The columns present in the data set are Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')
##########
The description of the data is 
              Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000
##########


## Let's check if there are any missing values in the data

In [8]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

So there is a missing data in Age column and a missing data in the Salary column

## Taking care of missing data

We can take care of the missing data using both sklearn and pandas package

### Using pandas

In [15]:
X_pd = dataset.drop('Purchased', axis = 1)
y_pd = dataset['Purchased']

X_pd['Age'] = X_pd['Age'].fillna(X_pd['Age'].mean())
X_pd['Salary'] = X_pd['Salary'].fillna(X_pd['Salary'].mean())

X = X_pd.iloc[:,:].values
y = y_pd.values

In [17]:
print(X)
print("#"*100)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
####################################################################################################
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Using sklearn

In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values


imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [20]:
print(X)
print("#"*100)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
####################################################################################################
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Encoding categorical data

### Encoding the Independent Variable

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# the first parameter for transformers is a name, the second one is the method that we wish to apply and the third one is the index of the data on which we want to apply the transformation
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [22]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [24]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [34]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [35]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [36]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [37]:
print(y_test)

[0 1]


## Feature Scaling

Can we use the column transformer to perform the feature scaling operation?

### without using column transformer

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [31]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [32]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]


### with using column transformer

In [44]:
ct = ColumnTransformer(transformers=[('scaler', StandardScaler(), [3,4])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))
X_test = np.array(ct.transform(X_test))

In [40]:
X_train

array([[-0.19159184384578545, -1.0781259408412422, 0.0, 0.0, 1.0],
       [-0.014117293757057777, -0.0701316764163537, 0.0, 1.0, 0.0],
       [0.566708506533324, 0.6335624327104549, 1.0, 0.0, 0.0],
       [-0.30453019390224867, -0.3078661727429786, 0.0, 0.0, 1.0],
       [-1.9018011447007988, -1.4204636155515817, 0.0, 0.0, 1.0],
       [1.1475343068237058, 1.2326533634535488, 1.0, 0.0, 0.0],
       [1.4379472069688968, 1.5749910381638883, 0.0, 1.0, 0.0],
       [-0.7401495441200351, -0.5646194287757332, 1.0, 0.0, 0.0]],
      dtype=object)

In [41]:
X_test

array([[-1.4661817944830124, -0.9069571034860726, 0.0, 1.0, 0.0],
       [-0.44973664397484414, 0.20564033932253056, 1.0, 0.0, 0.0]],
      dtype=object)